application_host: 127.0.0.1
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "smarthome"
run_live_consumption_subscriber: false
mqtt:
  run_mqtt: false
