services:
  frontend:
    build: frontend
    restart: always
    env_file:
      - frontend/.env
    ports:
      - "3030:3000"
  raspi-rust-api:
    build:
        context: raspi-rust-api
        dockerfile: Dockerfile.macos
    restart: always
    env_file:
      - raspi-rust-api/.env.prod
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env.db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
