# This is a basic workflow to help you get started with Actions

name: frontend_build_and_deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building frontend"
      - uses: actions/checkout@v3
      - name: Build
        run: sh frontend/build.sh